apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-hints
  namespace: logging
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: filestream
            id: kubernetes-container-logs-${data.kubernetes.pod.name}-${data.kubernetes.container.id}
            paths:
            - /var/log/containers/*-${data.kubernetes.container.id}.log
            parsers:
            - container: ~
            prospector:
             scanner:
               fingerprint.enabled: true
               symlinks: true
            file_identity.fingerprint: ~

    processors:
      - add_cloud_metadata:
      - add_host_metadata:

    output.logstash:
      hosts: ["${LOGSTASH_HOST:logstash}:${LOGSTASH_PORT:5044}"]
