apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: logging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: logging

---
apiVersion: v1
data:
  tail_container_parse.conf: |
    <parse>
      @type cri
    </parse>
kind: ConfigMap
metadata:
  name: tail-container-parse-override
  namespace: logging

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: fluentd
      serviceAccountName: fluentd
      # Enable tolerations if you want to run daemonset on control-plane nodes.
      # Recommended to disable on managed k8s.
      #tolerations:
      #- key: node-role.kubernetes.io/control-plane
      #  effect: NoSchedule
      #- key: node-role.kubernetes.io/master
      #  effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-graylog-arm64
        imagePullPolicy: IfNotPresent
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name:  FLUENT_GRAYLOG_HOST
            value: "graylog01.lab"
          - name:  FLUENT_GRAYLOG_PORT
            value: "12202"
          - name:  FLUENT_GRAYLOG_PROTOCOL
            value: "udp"
          - name:  FLUENTD_SYSTEMD_CONF
            value: "disable"
          - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
            value: >
                [
                "/var/log/containers/fluent*"
                ]
          #- name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
          #  value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            # ===========
            # Less memory leads to child process problems.
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        # When actual pod logs in /var/log/pods, the following lines should be used.
        - name: containerlogdirectory
          mountPath: /var/log/pods
          readOnly: true
        # ConfigMap:
        - name: tail-container-parse-override
          mountPath: /fluentd/etc/tail_container_parse.conf
          subPath: tail_container_parse.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      # When actual pod logs in /var/log/pods, the following lines should be used.
      - name: containerlogdirectory
        hostPath:
          path: /var/log/pods
      - name: tail-container-parse-override
        configMap:
          name: tail-container-parse-override
