services:
  mongodb:
    container_name: mongodb
    image: "mongo:${MONGODB_VERSION}"
    volumes:
      - "mongodb_data:/data/db"
    networks:
      - graylog_network
    restart: "always"

  opensearch:
    container_name: opensearch
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms2g -Xmx2g -Dlog4j2.formatMsgNoLookups=true"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: "false"
      DISABLE_INSTALL_DEMO_CONFIG: "true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      DISABLE_SECURITY_PLUGIN: "true" # disables security plugin entirely in OpenSearch by setting plugins.security.
    image: "opensearchproject/opensearch:${OPENSEARCH_VERSION}"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    ports:
    - "9200:9200/tcp"   # es ports
    networks:
      - graylog_network
    volumes:
      - "opensearch_data:/usr/share/opensearch/data"
    restart: "always"

  graylog:
    container_name: graylog
    image: "graylog/graylog-enterprise:6.0.1-1"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 941828f6268291fa3aa87a866e8367e609434f42761bdf02dc7fc7958897bae6
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
      - "443:443/tcp"     # Server API
      - "514:514/udp"     # Syslog UDP
      - "514:514/tcp"     # Syslog TCP
      - "5044:5044/tcp"   # Beats
      - "5050:5050/tcp"   # RAW TCP
      - "5050:5050/udp"   # RAW UDP
      - "5555:5555/tcp"   # CEF TCP
      - "5555:5555/udp"   # CEF UDP
      - "5556:5556/tcp"   # Palo Alto Networks v9+ TCP
      - "5557:5557/tcp"   # Palo Alto Networks v8.x TCP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
    networks:
      - graylog_network
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
      - "graylog_config:/usr/share/graylog/data/config"
    restart: "always"


volumes:
  mongodb_data:
    name: "mongodb_data"
  opensearch_data:
    name: "opensearch_data"
  graylog_data:
    name: "graylog_data"
  graylog_journal:
    name: "graylog_journal"
  graylog_config:
    name: "graylog_config"

networks:
  graylog_network: